import { Oghams } from '../../GlobalTypes';

export const staves = {
  [Oghams.Birch]: {
    name: 'Birch',
    image: `${process.env.PUBLIC_URL}/icons/ogham/birch.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Birch} stave to increase Magic Defense.`,
  },
  [Oghams.Rowan]: {
    name: 'Rowan',
    image: `${process.env.PUBLIC_URL}/icons/ogham/rowan.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Rowan} stave to increase Magic Power.`,
  },
  [Oghams.Alder]: {
    name: 'Alder',
    image: `${process.env.PUBLIC_URL}/icons/ogham/alder.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Alder} stave to halve Enchantment ability cost this turn.`,
  },
  [Oghams.Willow]: {
    name: 'Willow',
    image: `${process.env.PUBLIC_URL}/icons/ogham/willow.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Willow} stave to make this characters next Enchantment free.`,
  },
  [Oghams.Ash]: {
    name: 'Ash',
    image: `${process.env.PUBLIC_URL}/icons/ogham/ash.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Ash} stave to gain a magic damage multiplier next turn.`,
  },
  [Oghams.Hawthorn]: {
    name: 'Hawthorn',
    image: `${process.env.PUBLIC_URL}/icons/ogham/hawthorn.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Hawthorn} stave to increase physical defense.`,
  },
  [Oghams.Oak]: {
    name: 'Oak',
    image: `${process.env.PUBLIC_URL}/icons/ogham/oak.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Oak} stave to increase physical power. `,
  },
  [Oghams.Holly]: {
    name: 'Holly',
    image: `${process.env.PUBLIC_URL}/icons/ogham/holly.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Holly} stave to halve Feat ability cost this turn.`,
  },
  [Oghams.Hazel]: {
    name: 'Hazel',
    image: `${process.env.PUBLIC_URL}/icons/ogham/hazel.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Hazel} stave to to make this characters next Feat free.`,
  },
  [Oghams.Apple]: {
    name: 'Apple',
    image: `${process.env.PUBLIC_URL}/icons/ogham/apple.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Apple} stave to gain a physical damage multiplier next turn.`,
  },
  [Oghams.Vine]: {
    name: 'Grape Vine',
    image: `${process.env.PUBLIC_URL}/icons/ogham/vine.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Vine} stave to give a buff/debuff to another.`,
  },
  [Oghams.Ivy]: {
    name: 'Ivy',
    image: `${process.env.PUBLIC_URL}/icons/ogham/ivy.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Ivy} stave to pull a random buff/debuff from another.`,
  },
  [Oghams.Reed]: {
    name: 'Reed',
    image: `${process.env.PUBLIC_URL}/icons/ogham/reed.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Reed} stave to give this character a random buff.`,
  },
  [Oghams.Blackthorn]: {
    name: 'Blackthorn',
    image: `${process.env.PUBLIC_URL}/icons/ogham/blackthron.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Blackthorn} stave to take a buff/debuff from another.`,
  },
  [Oghams.Elder]: {
    name: 'Elder',
    image: `${process.env.PUBLIC_URL}/icons/ogham/elder.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Elder} stave to copy a buff/debuff from one to another.`,
  },
  [Oghams.Fir]: {
    name: 'White Fir',
    image: `${process.env.PUBLIC_URL}/icons/ogham/fir.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Fir} stave to combo with an action.`,
  },
  [Oghams.Gorse]: {
    name: 'Gorse',
    image: `${process.env.PUBLIC_URL}/icons/ogham/gorse.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Gorse} stave to combo with an action.`,
  },
  [Oghams.Heather]: {
    name: 'Heather',
    image: `${process.env.PUBLIC_URL}/icons/ogham/heather.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Heather} stave to combo with an action.`,
  },
  [Oghams.Poplar]: {
    name: 'Poplar',
    image: `${process.env.PUBLIC_URL}/icons/ogham/poplar.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Poplar} stave to combo with an action.`,
  },
  [Oghams.Yew]: {
    name: 'Yew',
    image: `${process.env.PUBLIC_URL}/icons/ogham/yew.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Yew} stave to combo with an action.`,
  },
  [Oghams.Grove]: {
    name: 'Grove',
    image: `${process.env.PUBLIC_URL}/icons/ogham/grove.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Grove} Forfeda!`,
  },
  [Oghams.Spindle]: {
    name: 'Spindle',
    image: `${process.env.PUBLIC_URL}/icons/ogham/spindle.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Spindle} Forfeda!`,
  },
  [Oghams.Honeysuckle]: {
    name: 'Honeysuckle',
    image: `${process.env.PUBLIC_URL}/icons/ogham/honeysuckle.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Honeysuckle} Forfeda!`,
  },
  [Oghams.Gooseberry]: {
    name: 'Gooseberry',
    image: `${process.env.PUBLIC_URL}/icons/ogham/gooseberry.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.Gooseberry} Forfeda!`,
  },
  [Oghams.WitchHazel]: {
    name: 'Witch Hazel',
    image: `${process.env.PUBLIC_URL}/icons/ogham/witchHazel.svg`,
    apCost: 1,
    remainingUses: 1,
    detailedInfo: `Burst a ${Oghams.WitchHazel} Forfeda!`,
  },
};
